`wheel-ctk-name-gen` part of `gha-tools`
rapidsai/shared-action-workflows pull request #91
Opened 2023-05-18 16:00 UTC by divyegala

Relies on https://github.com/rapidsai/gha-tools/pull/55

Closes https://github.com/rapidsai/shared-action-workflows/issues/77

2023-05-22 19:52 UTC, vyasr requested changes
The changes in this PR aren't sufficient. If you inspect the wheels uploaded by [the rmm test PR](https://github.com/rapidsai/rmm/pull/1270) (let me know if you need help finding those), you'll notice that you no longer have separate CUDA 11 and CUDA 12 wheels. Instead you have a single set of wheels like `rmm_wheel_python_310_x86_64.tar.gz`. The problem is that the `rapids-upload-wheels-to-s3` script run in the "Upload wheels to downloads.rapids.ai" step below [uses `rapids-package-name`](https://github.com/rapidsai/gha-tools/blob/main/tools/rapids-upload-wheels-to-s3#L7), which in turn has [an implicit dependence on `RAPIDS_PY_WHEEL_NAME` being set](https://github.com/rapidsai/gha-tools/blob/main/tools/rapids-package-name#L47). The simplest solution for now is probably to set that variable in the line running that script in both build workflows. You will also need to combine the upload step into this step so that the variable is available.

2023-05-22 20:02 UTC, divyegala commented on .github/workflows/wheels-manylinux-build.yml
> +        cuda_version="$(/tmp/gha-tools/tools/rapids-wheel-ctk-name-gen ${{ matrix.ctk }})"
I don't think we need to `export` this variable, but otherwise yes the variable can b e reused for brevity

2023-05-22 20:45 UTC, divyegala commented
@vyasr Looks like the right wheels are now being uploaded https://downloads.rapids.ai/ci/rmm/pull-request/1270/904c7a1/

2023-05-23 16:32 UTC, vyasr commented
@divyegala I've merged the gha-tools PR. I'll trigger a rebuild of the containers so that they pick up the latest gha-tools. Can you update this workflow to remove the temp clone? Then we can rerun CI on the rmm PR to verify that things are working as expected.

2023-05-23 16:33 UTC, divyegala commented
Thanks @vyasr! Can you share a URL so that I can follow when new containers are pushed?

2023-05-23 16:37 UTC, vyasr commented
It should show up [in the repo's Actions tab](https://github.com/rapidsai/cibuildwheel-imgs/actions).

2023-05-23 18:21 UTC, vyasr approved these changes
Couple of small typo fixes, otherwise this looks good to go once tests pass on the rmm PR.

2023-05-23 18:21 UTC, vyasr commented on .github/workflows/wheels-manylinux-build.yml
> +        # The variable $PIP_CU_VERSION needs to be used as an un-evaluated string by downstream libraries
```suggestion
        # The variable $PIP_CU_VERSION needs to be used as an unevaluated string by downstream libraries
```

2023-05-23 18:53 UTC, merged